app:
  name: tiklab-matflow
spring:
  profiles:
    active: test

APP_HOME: ${APP_HOME}
application: matFlow

server:
  port: 8092

jdbc:
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://172.11.1.10:3306/tiklab_matflow?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  username: root
  password: darth2020

#plugin config
PROJECT_HOME: ${user.home}/matflow/${app.name}
plugin:
  path: ${PROJECT_HOME}/plugin

#dfs config
dfs:
  server:
    enabled: false
    mode: server
    port: 4000
    datapath: ${PROJECT_HOME}/files
  client:
    url: 172.11.1.17:4000
    bucket: ${app.name}

#dcs config
dcs:
  server:
    enabled: false
    mode: server
    port: 5000
    datapath: ${PROJECT_HOME}/caches
  client:
    url: 172.11.1.17:5000
    bucket: ${app.name}

#dcs config
dss:
  server:
    enabled: false
    mode: server
    port: 6000
    datapath: ${PROJECT_HOME}/index
  client:
    url: 172.11.1.17:6000
    bucket: ${app.name}

datapath: ${PROJECT_HOME}/caches

#eas config
eas:
  embbed:
    enable: false
  server:
    port: 8080
  address: http://localhost:8080
  web:
    address: http://localhost:8080
  jdbc:
    driverClassName: ${jdbc.driverClassName}
    url: ${jdbc.url}
    username: ${jdbc.username}
    password: ${jdbc.password}
  mysql:
    name: tiklab_matflow


#mysql config
mysql:
  embbed:
    enable: false
  server:
    port: 3306
  version: mysql-8.0.28
  name: tiklab_matflow

#homes
homes:
  address: http://172.11.1.11:8080

#license
licences:
  path: ${APP_HOME}/licences

#file
file:
  path: http://file.dev.tiklab.net

#git
git:
  gitee:
    client:
      id: 50bf05d8e3ef61340e9f0f1b5baa3cc7f45e009d5fdfa47a4833fc2283efac1d
      secret: 12ec3c04ce71d926740b14b802c0dfd90ea29420c3a5a77173c98bd230ac73a5
    callback:
      url: http%3A%2F%2Fpipeline-ce.test.matflow.net%2F%23%2Findex%2Ftask%2Fconfig
  github:
    client:
      id: c5b8d1ef3796f8c60915
      secret: ff030563b66de5dcffc375ae7950d89179713751
    callback:
      url: http://matFlow-ce.test.matflow.net/#/index/task/config










